security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: auto
    providers:
        users_in_memory:
            memory:
                users:
#                    @Dm1n
                    'admin@covid.tn': { password: '$argon2id$v=19$m=65536,t=4,p=1$FVkjJw1BWWZP5mLYypgNJA$v5FadhQfTgVZ8ftsacJ1Lps+Ld+tZfHgbQn9v9HPG8Y' , roles: 'ROLE_ADMIN' }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            anonymous: ~
            form_login:
                login_path: 'login'
                check_path: 'login'
                default_target_path: 'dashboard'
            logout:
                path: 'logout'
                target: 'login'
            provider: users_in_memory
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }