
App\Domain\Model\DayNumbers\DayNumbers:
  type: entity
  table: day_numbers
  repositoryClass: App\Infrastructure\Repository\Doctrine\DayNumbersRepository
  id:
    id:
      type: string
      generator:
        strategy: UUID
  fields:
    newCases:
      type: integer
    newDeaths:
      type: integer
    newHealed:
      type: integer
    date:
      type: date
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
  manyToOne:
    town:
      targetEntity: App\Domain\Model\Town\Town
      inversedBy: dayNumbers
