
App\Domain\Model\Patient\Patient:
  type: entity
  table: patient
  repositoryClass: App\Infrastructure\Repository\Doctrine\PatientRepository
  id:
    id:
      type: string
      generator:
        strategy: UUID
  fields:
    email:
      type: string
      length: 255
    lastName:
      type: string
      length: 255
    firstName:
      type: string
      length: 255
    gender:
      type: boolean
    age:
      type: integer
    zipCode:
      type: string
      length: 255
    street:
      type: string
      length: 255
    phone:
      type: string
      length: 255
      nullable: true
    mobile:
      type: string
      length: 255
    antecedent:
      type: json_array
    treatment:
      type: json_array
    symptoms:
      type: json_array
    symptomsStartDate:
      type: date
    emergencyVisited:
      type: boolean
    doctorVisited:
      type: boolean
    temperature:
      type: float
    breathingFrequency:
      type: float
    oxygenSaturation:
      type: float
    heartBeat:
      type: float
  manyToOne:
    town:
      targetEntity: App\Domain\Model\Town\Town
      inversedBy: patients

