
App\Domain\Model\Town\Town:
  type: entity
  table: town
  repositoryClass: App\Infrastructure\Repository\Doctrine\TownRepository
  id:
    id:
      type: string
      generator:
        strategy: UUID
  fields:
    name:
      type: string
      length: 255
  oneToMany:
    patients:
      targetEntity: App\Domain\Model\Patient\Patient
      orphanRemoval: true
      mappedBy: town
    dayNumbers:
      targetEntity: App\Domain\Model\DayNumbers\DayNumbers
      orphanRemoval: true
      mappedBy: town