town_create:
  path: 'admin/town/create'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Town\CreateTownAction' }

town_list:
  path: 'admin/town/list'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Town\ListTownAction' }

admin_patient_create:
  path: 'admin/patient/create'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Patient\CreatePatientAction' }

admin_patient_update:
  path: 'admin/patient/update/{id}'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Patient\UpdatePatientAction' }

admin_patient_delete:
  path: 'admin/patient/delete/{id}'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Patient\DeletePatientAction' }

admin_patient_view:
  path: 'admin/patient/view/{id}'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Patient\ViewPatientAction' }

admin_front_patient_list:
  path: 'admin/patient/list/site'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Patient\FrontListPatientAction' }
admin_back_patient_list:
  path: 'admin/patient/list/admin'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Patient\BackListPatientAction' }
admin_day_numbers_create:
  path: 'admin/day-numbers/create'
  defaults: { _controller: 'App\Infrastructure\Back\Action\DayNumbers\CreateDayNumbersAction' }

admin_day_numbers_list:
  path: 'admin/day-numbers/list'
  defaults: { _controller: 'App\Infrastructure\Back\Action\DayNumbers\ListDayNumbersAction' }

login:
  path: 'admin/login'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Login\LoginUserAction' }

logout:
  path: 'admin/logout'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Login\LogoutUserAction' }

dashboard:
  path: '/admin'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Dashboard\DashboardAction' }
home:
  path: '/'
  defaults: { _controller: 'App\Infrastructure\Front\Action\Home\HomeAction' }

patient_create:
  path: '/patient/create'
  defaults: { _controller: 'App\Infrastructure\Front\Action\Patient\CreatePatientAction' }