town_create:
  path: 'admin/town/create'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Town\CreateTownAction' }

town_list:
  path: 'admin/town/list'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Town\ListTownAction' }

login:
  path: 'admin/login'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Login\LoginUserAction' }

logout:
  path: 'admin/logout'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Login\LogoutUserAction' }

dashboard:
  path: '/admin'
  defaults: { _controller: 'App\Infrastructure\Back\Action\Dashboard\DashboardAction' }
home:
  path: '/'
  defaults: { _controller: 'App\Infrastructure\Front\Action\Home\HomeAction' }