parameters:
    contact_mail: '%env(CONTACT_MAIL)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'


    App\Infrastructure\Back\Action\:
        resource: '../src/Infrastructure/Back/Action'
        tags: ['controller.service_arguments']
    App\Infrastructure\Front\Action\:
        resource: '../src/Infrastructure/Front/Action'
        tags: ['controller.service_arguments']

    App\Domain\Model\Town\TownRepositoryInterface:  '@App\Infrastructure\Repository\Doctrine\TownRepository'
    App\Domain\Model\Contact\ContactRepositoryInterface:  '@App\Infrastructure\Repository\Doctrine\ContactRepository'



